### ISSUE TITLE
通过writeLocal判断创建是batch/shard的逻辑是否反了？

### ISSUE THREAD

**Issue by Aireed** [itinycheng/flink-connector-clickhouse#1]
![image](https://user-images.githubusercontent.com/8862395/141061037-d15a8ddf-8a74-4fd1-9130-20686ff64a84.png)
这个判断是batch还是shard 逻辑是不是应该改成这样？原来的逻辑写反了？？

**Comment by itinycheng** [comment]
> ![image](https://user-images.githubusercontent.com/8862395/141061037-d15a8ddf-8a74-4fd1-9130-20686ff64a84.png) 这个判断是batch还是shard 逻辑是不是应该改成这样？原来的逻辑写反了？？


HI Aireed:
原有逻辑是正确的，`README.md`上对`write-local`有参数说明；
这个参数在`Distributed`表中才会起到作用，在`非Distributed`中需将`write-local`设置为`false`，不然会报错；
`createShardOutputFormat`作用是获取`Distributed`表对应的`Local`表并创建`OutputFormat`，后续会将数据直接写入`Local`表。
