### ISSUE TITLE
配置properties.*属性，报错

### ISSUE THREAD

**Issue by zaorangyang** [itinycheng/flink-connector-clickhouse#101]
我用properties.配置了一个属性，正确的行为应该是可以透传给clickhouse-server的，但是用sql-client.sh提交job时，flink报错：
![image](https://github.com/itinycheng/flink-connector-clickhouse/assets/45813655/e944755a-bc9e-4eb0-8690-bff0c7820ab2)

**Comment by itinycheng** [comment]
@zaorangyang 
支持`properties.`的代码在master分支：https://github.com/itinycheng/flink-connector-clickhouse/commit/23f5bf24cd9673ffe7c748dde64dc4db5f521ab1
