### ISSUE TITLE
flink cdc  to clickhouse

### ISSUE THREAD

**Issue by fancky2019** [itinycheng/flink-connector-clickhouse#113]
this is my config below

CREATE TABLE demo (
 *******
) WITH (
    'connector' = 'clickhouse',
    'url' = 'clickhouse://172.16.112.137:8123',
    'database-name' = 'default',
    'table-name' = 'demo',
    'sink.batch-size' = '500',
    'sink.flush-interval' = '1000',
    'sink.ignore-delete'='false',
    'sink.update-strategy'='update',
    'sink.max-retries' = '3'
);

when I  execute delete or update statement  in mysql ,clickhouse  data do not change.
can you help me?

**Comment by itinycheng** [comment]
Hi @fancky2019 

Your configs look fine, it's better to do some breakpoint testing, the code for update/delete is here: https://github.com/itinycheng/flink-connector-clickhouse/blob/master/flink-connector-clickhouse/src/main/java/org/apache/flink/connector/clickhouse/internal/executor/ClickHouseUpsertExecutor.java
