### ISSUE TITLE
请问要在flink/lib目录放哪些包才可以运行呢？

### ISSUE THREAD

**Issue by lliuql** [itinycheng/flink-connector-clickhouse#114]
`Flink SQL>  
>  INSERT INTO enriched_orders
>  SELECT o.*, p.name, p.description, s.shipment_id, s.origin, s.destination, s.is_arrived
>  FROM orders AS o
>  LEFT JOIN products AS p ON o.product_id = p.id
>  LEFT JOIN shipments AS s ON o.order_id = s.order_id;
[ERROR] Could not execute SQL statement. Reason:
java.lang.ClassNotFoundException: org.apache.http.client.utils.URIBuilder
`

环境：flink1.17;    maven 编译profile选择的是release.
目前打算看哪些包报错就往lib加哪些包。不过还是想问一下，到底具体哪些是需要放到flink/lib的。
要是能得到您的回答，不胜感激哈

**Comment by fancky2019** [comment]
1.16 release jar  + clcickhouse jdbc

**Comment by fancky2019** [comment]
make sure you can connect clickhouse successfully,  you can config  /etc/clickhouse-server/config.xml   with <listen_host>0.0.0.0</listen_host>  by ipv4.

flink/lib  jars
release 1.16 jar 
clickhouse -jdbc

**Comment by fancky2019** [comment]
make sure you can connect clickhouse successfully,  you can config  /etc/clickhouse-server/config.xml   with <listen_host>0.0.0.0</listen_host>  by ipv4.

flink/lib  jars
release 1.16 jar 
clickhouse -jdbc
