### ISSUE TITLE
最新的1.71需要jdk11吗？用jdk8报错了

### ISSUE THREAD

**Issue by huotianyu** [itinycheng/flink-connector-clickhouse#115]
check报如下错误
org.openjdk.javax.tools.JavaFileManager$Location

![1110](https://github.com/itinycheng/flink-connector-clickhouse/assets/4433745/e3dfa1ca-7bdc-4bd4-bfc3-3ac9e19085e4)

**Comment by itinycheng** [comment]
> check报如下错误 org.openjdk.javax.tools.JavaFileManager$Location
> 
> ![1110](https://private-user-images.githubusercontent.com/4433745/297956569-e3dfa1ca-7bdc-4bd4-bfc3-3ac9e19085e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDM0MDksIm5iZiI6MTcwNjAwMzEwOSwicGF0aCI6Ii80NDMzNzQ1LzI5Nzk1NjU2OS1lM2RmYTFjYS03YmRjLTRiZDQtYmZjMy0zYWM5ZTE5MDg1ZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMDk0NTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDgxZTdjODY4MDc3ZjlmODdmOWJlN2VkNzNlZDFlYWI3ZDA3ZWM3MjQ0NTkxZTY5Y2ZhYWY0NzM4ZjI3MDcyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dMbYV-dc-_t-oUf9WHLQgraWAv6CqEupFUli3HMY3Os)

hi @huotianyu:
项目同时支持jdk8/jdk11，这个报错应该和你Idea环境相关，报错内容太简短，我看不出原因；
你可以直接`mvn clean package -DskipTests` 编译看下；
