### ISSUE TITLE
 Execution default of goal io.github.zentol.japicmp:japicmp-maven-plugin:0.16.0_m325:cmp failed: version can neither be null, empty nor blank

### ISSUE THREAD

**Issue by jweicai** [itinycheng/flink-connector-clickhouse#119]
[INFO] Flink : Connectors : Clickhouse Parent ............. SUCCESS [  7.019 s]
[INFO] Flink : Connectors : Clickhouse .................... FAILURE [ 11.835 s]
[INFO] Flink : Connectors : SQL : Clickhouse .............. SKIPPED
[INFO] Flink : Connectors : Clickhouse : E2E Tests ........ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.104 s
[INFO] Finished at: 2024-03-14T21:11:57+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.github.zentol.japicmp:japicmp-maven-plugin:0.16.0_m325:cmp (default) on project flink-connector-clickhouse: Execution default of goal io.github.zentol.japicmp:japicmp-maven-plugin:0.16.0_m325:cmp failed: version can neither be null, empty nor blank -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command

**Comment by itinycheng** [comment]
Hi @jweicai 
It's a known compilation issue, remove the plugin in `pom.xml` as a temporary solution:
```
        <plugin>
		<!-- activate API compatibility checks -->
		<groupId>io.github.zentol.japicmp</groupId>
		<artifactId>japicmp-maven-plugin</artifactId>
	</plugin>
```

**Comment by jweicai** [comment]
Thanks, it works
