### ISSUE TITLE
Support URLs with query params

### ISSUE THREAD

**Issue by sap1ens** [itinycheng/flink-connector-clickhouse#129]
Currently, this connector doesn't support URLs with query params, e.g. `?ssl=true`. 

Simply removing the trailing slash from the base URL should solve it. 

I opened https://github.com/itinycheng/flink-connector-clickhouse/pull/108, but it was closed.

**Comment by czy006** [comment]
@sap1ens connector now have updated clickhouse client which may cause your code to need to be reimplemented. Maybe that's why it's closed. If you don't mind, I can turn it back on

**Comment by czy006** [comment]
![image](https://github.com/itinycheng/flink-connector-clickhouse/assets/28348735/e25ba0ec-91fb-4303-bddd-08893c55734c)

**Comment by czy006** [comment]
`
CREATE TABLE t_user (
    -- `id` DECIMAL,
    `col1` STRING,
    `col2` STRING,
    `col3` STRING
) WITH (
    'connector' = 'clickhouse',
    'url' = 'jdbc:ch://xxx.xxx.xxx:8123?useSSL=false',
    'database-name' = 'persona',
    'table-name' = 'persona_wide_table',
    'sink.batch-size' = '500',
    'sink.flush-interval' = '1000',
    'sink.max-retries' = '3'
);

-- read data from clickhouse 
SELECT * from t_user limit 10;` @sap1ens I test it can select it
