### ISSUE TITLE
[Bug]: UInt Type Not Supprot to Read Or Write

### ISSUE THREAD

**Issue by czy006** [itinycheng/flink-connector-clickhouse#136]
### What happened?

UInt Type Not Supprot to Read Or Write on connector

### Affects Versions

master

### How to reproduce

![img_v3_02bq_29471db6-b13b-4022-ab7d-a0e95ab2000g](https://github.com/itinycheng/flink-connector-clickhouse/assets/28348735/5796c56c-4600-4b28-846e-03db9968fb94)

Clickhouse Create Table SQL
```
CREATE TABLE test.persona_wide_table
(

    `id` UInt64,
    `col1` String,
    `col2` String,
    `col3` String
)
ENGINE = MergeTree
ORDER BY id
SETTINGS index_granularity = 8192;
```

Flink SQL Create And Select SQL
```
CREATE TABLE test
(
    `id` DECIMAL,
    `col1` String,
    `col2` String,
    `col3` String
) WITH (
    'connector' = 'clickhouse',
    'url' = 'jdbc:ch://xxxx:8123?useSSL=false',
    'database-name' = 'test',
    'table-name' = 'persona_wide_table',
    'sink.batch-size' = '500',
    'sink.flush-interval' = '1000',
    'sink.max-retries' = '3'
);
```
ClickHouseDataType
![image](https://github.com/itinycheng/flink-connector-clickhouse/assets/28348735/009ef11d-6129-4f0f-a459-5986cf78c673)

### Anything else

- Support read UnsignedLong Or UnsignedInteger

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itinycheng** [comment]
Hi @czy006 :
I'm working on data conversion logic for compatibility with `clickhouse-jdbc 0.6`.
Can you assign this issue to me?

**Comment by itinycheng** [comment]
Hi @czy006 

I'm going to take over this issue if there are no more questions.
Hope to get your feedback.
