### ISSUE TITLE
flink1.17.2  clickhouse catalog集成kafka 报错：创建kafka表时报错

### ISSUE THREAD

**Issue by jinglala1** [itinycheng/flink-connector-clickhouse#139]
建表时，告诉我：RuntimeException occurred: Could not execute CreateTable in path `clickhouse`.`ads_dft_zhyw`.`kafka_equipment2`，是因为我的clickhouse的配置有问题妈还是什么

**Comment by jinglala1** [comment]
![Uploading 62107cf360b4c217c90ed187da181b9.png…]()

**Comment by czy006** [comment]
@jinglala1 use bug template report and provide relevant error information
