### ISSUE TITLE
支持 URL后面添加socket_timeout？

### ISSUE THREAD

**Issue by qiunanx** [itinycheng/flink-connector-clickhouse#150]
### What happened?

String address = “jdbc:clickhouse://10.100.xx.xxx:8123?socket_timeout=300000”;

### Affects Versions

1.18

### What are you seeing the problem on?

Clickhouse-Client

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itinycheng** [comment]
Hi @qiunanx 
之前已经有PR，支持了带参数的url，不过一直没Merge；
可以先关注下：https://github.com/itinycheng/flink-connector-clickhouse/pull/143
