### ISSUE TITLE
The db history topic is missing. You may attempt to recover it by reconfiguring the connector to SCHEMA_ONLY_RECOVERY

### ISSUE THREAD

**Issue by mjp27258** [itinycheng/flink-connector-clickhouse#17]
In initail mode，the data was synchronized to the Clickhouse, but an error caused the task to fail

**Comment by itinycheng** [comment]
This seems not an exception caused by the ClickHouse connector.
If you are sure about that, please post the full stack trace, version info, etc.

Here is a similar issue:
https://github.com/ververica/flink-cdc-connectors/issues/678

**Comment by mjp27258** [comment]
通过升级flink-connector-mysql-cdc 至2.1.1解决
