### ISSUE TITLE
why ClickHouseBatchExecutor#addToBatch() deal with UPDATE_AFTER ?

### ISSUE THREAD

**Issue by liyubin117** [itinycheng/flink-connector-clickhouse#2]
in my opinion, ClickHouseBatchExecutor is used in append-only scenario, but in fact, it also deal with update event

**Comment by itinycheng** [comment]
> in my opinion, ClickHouseBatchExecutor is used in append-only scenario, but in fact, it also deal with update event

Yes, you are right.
ClickHouseBatchExecutor is only used in the append-only scenario. 
In the current code, the update event won't enter `ClickHouseBatchExecutor.addToBatch`; the code will run normally.
The current code causes misunderstanding; I will fix it.
