### ISSUE TITLE
How to guarantee exactly-once semantics?

### ISSUE THREAD

**Issue by LuPan2015** [itinycheng/flink-connector-clickhouse#20]
Since clickhouse does not support transactions, how to ensure exactly-once semantics when flink writes？

**Comment by itinycheng** [comment]
The project can guarantee idempotent when using the MergeTree engine but not exactly-once.
In my option, flink can keep end-to-end exactly-once when both endpoints support transactions.

**Comment by itinycheng** [comment]
> Since clickhouse does not support transactions, how to ensure exactly-once semantics when flink writes？

The project can guarantee `idempotent` when using the MergeTree engine but not `exactly-once`.
In my view, flink can keep end-to-end `exactly-once` when both endpoints support transactions.
