### ISSUE TITLE
How to support ClickHouse source in branch 1.12 ?

### ISSUE THREAD

**Issue by LinhaiXu** [itinycheng/flink-connector-clickhouse#23]
ClickHouse Source is only supported by Flink 1.13(or higher) in your project, is there any way support ClickHouse Source in Flink 1.12?

**Comment by itinycheng** [comment]
Yes, but needs a little work.
1. Checkout branch release-1.13, then modify the flink dependency version to 1.12.x;
2. Execute the command `mvn clean package -DskipTests` to compile the project and fix compile error.
3. The compiled package is available under flink 1.12.x;

**Comment by LinhaiXu** [comment]
> Yes, but needs a little work.
> 
> 1. Checkout branch release-1.13, then modify the flink dependency version to 1.12.x;
> 2. Execute the command `mvn clean package -DskipTests` to compile the project and fix compile error.
> 3. The compiled package is available under flink 1.12.x;
