### ISSUE TITLE
maven package not found javac

### ISSUE THREAD

**Issue by imiros** [itinycheng/flink-connector-clickhouse#29]
需要在pom添加如下引用。但不知道为啥，作者知道么
`<dependency>
			<groupId>com.google.errorprone</groupId>
			<artifactId>javac</artifactId>
			<version>9+181-r4173-1</version>
		</dependency>`

**Comment by imiros** [comment]
报错信息：Failed to read artifact descriptor for com.google.errorprone:javac:jar:9+181-r4173-1

**Comment by itinycheng** [comment]
您好，这个应该是jdk版本的问题？
我没遇到过这个问题，也不太清楚具体问题发生场景，sorry；

**Comment by imiros** [comment]
我猜测是java问题。因为我项目用的java11，所以后面也有提问是否考虑升级到11..问题不大，添加了pom引用就好了
