### ISSUE TITLE
flink sql sink到clickhouse

### ISSUE THREAD

**Issue by jetliu1711** [itinycheng/flink-connector-clickhouse#32]
你好，请问一下，flink sql sink到clickhouse中，clickhouse建表支持flink sql中ROW数据类型映射到clickhouse的JSON数据类型吗？

**Comment by itinycheng** [comment]
Sorry，不支持，刚知道新增了个JSON类型；
当前有个Map类型，不知道能否满足需求，具体看下readme;
最近没时间，过段才能去开发支持这个类型；

**Comment by jetliu1711** [comment]
>好的，谢谢你，那请问一下ROW能映射成map吗？

**Comment by itinycheng** [comment]
@jetliu1711 
Sorry，上一句没说太明白；
ROW没办法直接映射到Map，本身两个类型都不兼容；
如果你的ROW结构是类似`Map<String, FixedType>`这种，那你可以直接写个UDF函数，对该列做ROW到Map的转换；
如果ROW中类型比较多样，可以将单列拆分为多列分别存储，写个UDTF；

**Comment by jetliu1711** [comment]
> @jetliu1711 Sorry，上一句没说太明白； ROW没办法直接映射到Map，本身两个类型都不兼容； 如果你的ROW结构是类似`Map<String, FixedType>`这种，那你可以直接写个UDF函数，对该列做ROW到Map的转换； 如果ROW中类型比较多样，可以将单列拆分为多列分别存储，写个UDTF；

我这边Row有很多列的情况，map实现不了，因为拆分开来的字段太多了，想存个类似json类型的数据，我在想想办法，谢谢你。

**Comment by jetliu1711** [comment]
> > @jetliu1711 Sorry，上一句没说太明白； ROW没办法直接映射到Map，本身两个类型都不兼容； 如果你的ROW结构是类似`Map<String, FixedType>`这种，那你可以直接写个UDF函数，对该列做ROW到Map的转换； 如果ROW中类型比较多样，可以将单列拆分为多列分别存储，写个UDTF；
> 
> 我这边Row有很多列的情况，map实现不了，因为拆分开来的字段太多了，想存个类似json类型的数据，我在想想办法，谢谢你。
你好，兄弟，你给的那个maven下载路径，包找不到。

**Comment by itinycheng** [comment]
没deploy maven中央仓；
得自己手动打包`mvn clean package -DskipTests`

**Comment by jetliu1711** [comment]
> 没deploy maven中央仓； 得自己手动打包`mvn clean package -DskipTests`

好的，兄弟，在请教一个问题哈，是不是用jdbc也不支持json数据类型的写入？

**Comment by itinycheng** [comment]
Jdbc 好像复合类型都不支持，最后幸苦给个star吧，谢谢。

**Comment by jetliu1711** [comment]
> flink-connector-jdbc 好像复合类型都不支持; clickhouse-jdbc是支持所有类型的； 最后幸苦给个star吧，谢谢。

嗯嗯，好的，兄弟，刚才下载咱们master分支，非常慢，兄弟有编译的好jar吗？百度云啥的？

**Comment by jetliu1711** [comment]
> > flink-connector-jdbc 好像复合类型都不支持; clickhouse-jdbc是支持所有类型的； 最后幸苦给个star吧，谢谢。
> 
> 嗯嗯，好的，兄弟，刚才下载咱们master分支，非常慢，兄弟有编译的好jar吗？百度云啥的？

你好，咱们这个只能支持1.14.3的flink吗？

**Comment by jetliu1711** [comment]
> @jetliu1711
> 
> 1. 国内github页面访问确实不稳定，直接git checkout 应该好点；
> 2. 用1.13版本可以切换到 release-1.13分支；直接修改master的flink version也是可行的，不过得修复个编译问题，这个是flink包变更导致的；
>    ![image](https://user-images.githubusercontent.com/14097070/171141759-98d7c290-9cbc-4a9f-89dc-aeb32bc55a44.png)

好的，谢谢你。
