### ISSUE TITLE
mysql数据  slink clickhouse

### ISSUE THREAD

**Issue by zjialin** [itinycheng/flink-connector-clickhouse#35]
mysql数据  slink clickhouse 时间差了8小时，有什么参数可以设置吗

**Comment by itinycheng** [comment]
@zjialin 

时区问题有两种情况：
1. 这个有可能是clickhouse端导致的，确认下flink端和ClickHouse Server端配置的时区是否相同，在做分析；
2. Connector对数据类型为`TIMESTAMP_WITH_LOCAL_TIME_ZONE`的处理与其他时间类型不同，也可能会出现时差情况；
![image](https://user-images.githubusercontent.com/14097070/173021165-dc879c2d-4dc1-4ec5-a1f7-cf081f0db41b.png)
