### ISSUE TITLE
不支持指定sink 算子

### ISSUE THREAD

**Issue by v-qiunan** [itinycheng/flink-connector-clickhouse#37]
![image](https://user-images.githubusercontent.com/76831357/174563053-87c257cd-45cb-48a3-9f06-3c9a36d96033.png)
![image](https://user-images.githubusercontent.com/76831357/174563383-e718b92a-62d7-4797-b7a7-9e21fee226c9.png)

**Comment by v-qiunan** [comment]
我们可以将算子的并行度传到该方法的参数上

**Comment by itinycheng** [comment]
> org.apache.flink.connector.clickhouse.ClickHouseDynamicTableSink#getSinkRuntimeProvider 我们可以将算子的并行度传到该方法的参数上

Yes, nice idea.

**Comment by itinycheng** [comment]
@v-qiunan 
Already added. https://github.com/itinycheng/flink-connector-clickhouse/commit/fb0a878cb885818897085f074cb3bc2932434157
