### ISSUE TITLE
cast(timestamp as timestamp with local time zone) return the same value as input arg

### ISSUE THREAD

**Issue by liyubin117** [itinycheng/flink-connector-clickhouse#4]
in fact, at UTC+8 time zone, should return input arg - 8 hour

**Comment by itinycheng** [comment]
> in fact, at UTC+8 time zone, should return input arg - 8 hour

I did a test:

![image](https://user-images.githubusercontent.com/14097070/144350651-fa5cc384-2287-459f-9e00-60ea1f8330d3.png)

I think `TIMESTAMP '2021-12-02 00:00:00'` create a timestamp without time zone or UTC time, its millisecond is 1638403200000, its display with `timezone +8` is `2021-12-02 08:00:00`; 

`cast(TIMESTAMP '2021-12-02 00:00:00' as timestamp with local time zone)` will change the timezone to match table context, the millisecond will change to 1638374400000, but the time display won't change, so the result write to ClickHouse should also be `2021-12-02 00:00:00` if ClickHouse has the same timezone.

Am I wrong?
