### ISSUE TITLE
hudi同步ck数据报错

### ISSUE THREAD

**Issue by q443048756** [itinycheng/flink-connector-clickhouse#41]
1.报错Unable to create a sink for writing table 'default_catalog.default_database.ck'
2.报错java.lang.NoSuchMethodError: org.apache.flink.table.factories.DynamicTableFactory$Context.getCatalogTable()Lorg/apache/flink/table/catalog/CatalogTable;
3.maven无法拉取，改为手动下载1.12版本
4.flink版本为1.13.6

ck配置为:
'connector'='clickhouse'
'database-name'='XX'
'sink.batch-size'='500'
'sink.flush-interval'='1000'
'sink.max-retries'='3'
'table-name'='ck'
'url'='clickhouse://XX:9876'

希望得到帮助

**Comment by itinycheng** [comment]
> 1.报错Unable to create a sink for writing table 'default_catalog.default_database.ck'
> 2.报错java.lang.NoSuchMethodError: org.apache.flink.table.factories.DynamicTableFactory$Context.getCatalogTable()Lorg/apache/flink/table/catalog/CatalogTable;
> 3.maven无法拉取，改为手动下载1.12版本
> 4.flink版本为1.13.6
> 
> ck配置为:
> 'connector'='clickhouse'
> 'database-name'='XX'
> 'sink.batch-size'='500'
> 'sink.flush-interval'='1000'
> 'sink.max-retries'='3'
> 'table-name'='ck'
> 'url'='clickhouse://XX:9876'
> 
> 希望得到帮助

您好，

报错1应该是报错2引起的；

报错2好像是flink版本和connector版本不兼容导致的，当前项目有多个分支，如果你flink版本是1.13，请切换当前项目到release-1.13分支编译使用；

私人项目没maven公共仓账户，你自己可以mvn clean install -DskipTests 安装本地仓使用；

另外，可以先好好看下readme；
