### ISSUE TITLE
mysqlcdc同步到ck库的更新有问题

### ISSUE THREAD

**Issue by fejxc** [itinycheng/flink-connector-clickhouse#42]
mysql的源数据进行更新一条数据，ck库会把mysql更新的那条数据进行删除，不会新增一条更新后的新数据。

**Comment by itinycheng** [comment]
这个问题可能与[ClickHouseUpsertExecutor](https://github.com/itinycheng/flink-connector-clickhouse/blob/master/src/main/java/org/apache/flink/connector/clickhouse/internal/executor/ClickHouseUpsertExecutor.java ) 有关，关注下`executeBatch`方法；

`execute statements`顺序是 insert > update > delete；`delete statement`在一个batch中总是最后执行；
当flush batch size 大于1时又可能出现你说的这个问题，当前我还没太好的解决办法；

**Comment by walkhan** [comment]
@fejxc @itinycheng 测试的时候遇到了，现在有好的办法吗？我现在Flink1.14，看代码update策略代码是实现了，实测不支持
