### ISSUE TITLE
远程仓库在哪里？

### ISSUE THREAD

**Issue by weitianpei** [itinycheng/flink-connector-clickhouse#45]
请问在哪个远程仓库，可以拉到你的jar包呢？

**Comment by itinycheng** [comment]
> 请问在哪个远程仓库，可以拉到你的jar包呢？

需要自己手动打包，根据你的flink版本选择所需要的分支；
mvn clean install -DskipTests

**Comment by weitianpei** [comment]
请问你没有发布到中央仓库吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月11日(周四) 晚上9:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [itinycheng/flink-connector-clickhouse] 远程仓库在哪里？ (Issue #45)




  
请问在哪个远程仓库，可以拉到你的jar包呢？
  
需要自己手动打包，根据你的flink版本选择所需要的分支；
 mvn clean install -DskipTests

**Comment by itinycheng** [comment]
@weitianpei 
个人小项目，没deploy中央仓；

**Comment by weitianpei** [comment]
你不是已经被flink官网推荐了吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月11日(周四) 晚上9:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [itinycheng/flink-connector-clickhouse] 远程仓库在哪里？ (Issue #45)




 
@weitianpei
 个人小项目，没deploy中央仓；
