### ISSUE TITLE
ck的delete方式，是否能修改为insert加删除标志，而不是去执行alter语句

### ISSUE THREAD

**Issue by denganming** [itinycheng/flink-connector-clickhouse#47]

**Comment by itinycheng** [comment]
@denganming 
您说的确实是个问题，但加sign并不是每个引擎都支持，所以得有个比较普遍适用的方案；
最近我自己加了个update_after的转update，insert 或直接ignore的配置；
delete还没想太多，如果合适方案欢迎PR；

**Comment by walkhan** [comment]
@itinycheng update策略，在1.14代码中看到是有的，实测不支持
![image](https://user-images.githubusercontent.com/16821730/194836946-45fef9f7-9177-4fab-a8c3-85804c7f6b53.png)

那如何做到实时更新(delete和update)

**Comment by itinycheng** [comment]
`sink.update-strategy`的代码我并没合并到release-1.14分支；
不建议在Flink端生成类似update的操作，当前connector对update/delete支持也并不完善；
最好结合ClickHouse端表引擎来解决实际问题，单靠connector不太行；

**Comment by walkhan** [comment]
> `sink.update-strategy`的代码我并没合并到release-1.14分支； 不建议在Flink端生成类似update的操作，当前connector对update/delete支持也并不完善； 最好结合ClickHouse端表引擎来解决实际问题，单靠connector不太行；

@itinycheng ClickHouse我用了ReplacingMergeTree引擎，如果上游数据更新或者删除了，偶尔还是会出现数据多的问题。那么在1.15中sink.update-strategy能否规避这个问题呢？

**Comment by itinycheng** [comment]
> > `sink.update-strategy`的代码我并没合并到release-1.14分支； 不建议在Flink端生成类似update的操作，当前connector对update/delete支持也并不完善； 最好结合ClickHouse端表引擎来解决实际问题，单靠connector不太行；
> 
> @itinycheng ClickHouse我用了ReplacingMergeTree引擎，如果上游数据更新或者删除了，偶尔还是会出现数据多的问题。那么在1.15中sink.update-strategy能否规避这个问题呢？

Connector本身没办法保证`end-to-end exactly once`，具体数据多的原因给不出太多建议，最好根据自己场景排查下，如果是因为没有及时optimize table，可以另一个任务定时对表执行optimize操作；

**Comment by leosanqing** [comment]
我们实现了这个功能，可以选择逻辑删除还是物理删除，逻辑删除支持指定 字段。默认使用 insert 进行行更新

**Comment by itinycheng** [comment]
> 我们实现了这个功能，可以选择逻辑删除还是物理删除，逻辑删除支持指定 字段。默认使用 insert 进行行更新

这是个很好的功能，有时间欢迎提PR~
