### ISSUE TITLE
url地址是否支持集群模式？

### ISSUE THREAD

**Issue by kxbin** [itinycheng/flink-connector-clickhouse#48]
例如：
clickhouse://host1:8123,host2:8123,host3:8123

**Comment by itinycheng** [comment]
> 例如： clickhouse://host1:8123,host2:8123,host3:8123

您好，支持：
具体实现使用的是`clickhouse-jdbc`中的`BalancedClickhouseDataSource`

**Comment by kxbin** [comment]
@itinycheng 多谢，我测试一下看看

**Comment by kxbin** [comment]
您好，我在flink sql中测试集群模式的url，结果失败了

输入的url是
```
CREATE TABLE (
   略
) WITH  (
  'connector' = 'clickhouse',
  'url' = 'clickhouse://192.168.0.1:30004,192.168.0.2:30004,192.168.0.3:30004',
  其他参数略
)
```
调试得到的url是`clickhouse://null`
```
INFO  org.apache.flink.connector.clickhouse.internal.connection.ClickHouseConnectionProvider [] - connecting to clickhouse://null, database gaofang
```

我猜测是`org.apache.flink.configuration.ReadableConfig`读取url的时候，如果遇到逗号分隔会存在异常。

明天我在调试一下，如果有结果的话，我提交一个PR修复一下

如果您能给出一些指导，那就更好不过啦 :）

**Comment by kxbin** [comment]
是因为我有一个自定义的Properties文件弄错了，所以读取到的为null。 :joy:

flink sql 1.15.1，测试集群模式url是没问题的。

**Comment by itinycheng** [comment]
> 是因为我有一个自定义的Properties文件弄错了，所以读取到的为null。 😂
> 
> flink sql 1.15.1，测试集群模式url是没问题的。

@kxbin 

好的，有遇到问题，欢迎PR 🤝；
