### ISSUE TITLE
dialect

### ISSUE THREAD

**Issue by weitianpei** [itinycheng/flink-connector-clickhouse#57]
请问CLICKHOUSE 有dialect吗

**Comment by itinycheng** [comment]
> 请问CLICKHOUSE 有dialect吗

没太懂什么意思，没适配官方jdbc-connector的dialect；

**Comment by weitianpei** [comment]
我就是想问有没有适配官方的ck 版本的方言，这样就可以用ck的语法来操作数据



---Original---
From: ***@***.***&gt;
Date: Wed, Oct 26, 2022 14:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [itinycheng/flink-connector-clickhouse] dialect (Issue #57)




  
请问CLICKHOUSE 有dialect吗
  
没太懂什么意思，没适配官方jdbc-connector的dialect；
