### ISSUE TITLE
mysql两表在flink中做Regular Joins普通join，结果到ck中更新问题

### ISSUE THREAD

**Issue by xuexuebug** [itinycheng/flink-connector-clickhouse#59]
我在测试单表mysql-flink-clickhouse时，在MySQL新增、更新数据都会在ck中同步，但是在flink中两表join，在mysql中update一条数据他不会在ck中更新，而是新增了一条修改后的关联数据。

**Comment by itinycheng** [comment]
> 我在测试单表mysql-flink-clickhouse时，在MySQL新增、更新数据都会在ck中同步，但是在flink中两表join，在mysql中update一条数据他不会在ck中更新，而是新增了一条修改后的关联数据。

在有主键的情况下：ClickHouse Connector是接收上游的UPDATE_AFTER数据并生成Update语句，你可以结合分析下你的使用场景；
