### ISSUE TITLE
读取clickhouse的时候，不会一直读取，加载完了当前时间的数据，就退出了

### ISSUE THREAD

**Issue by xyhc** [itinycheng/flink-connector-clickhouse#62]
/**
     * 关联clickhouse, 建表a
     */
    tEnv.executeSql(
      s"""
         |CREATE TABLE a (
         | channel_id INT,
         | code_id INT,
         | account_id BIGINT,
         | create_time TIMESTAMP_LTZ(3),
         | primary key(channel_id,code_id,account_id) NOT ENFORCED,
         | WATERMARK FOR create_time AS create_time - INTERVAL '1' HOUR
         |) WITH (
         |  'connector' = 'clickhouse',
         |  'url' = '$ckURL',
         |  'database-name' = 'db',
         |  'username' = '$ckUser',
         |  'password' = '$ckPassword',
         |  'table-name' = 'a',
         |  'scan.partition.column' = '$scanPartitionColumn',
         |  'scan.partition.num' = '$scanPartitionNum',
         |  'scan.partition.lower-bound' = '$scanPartitionLowerBound',
         |  'scan.partition.upper-bound' = '$scanPartitionUpperBound'
         |)
         |""".stripMargin
    )

    val resultTable: Table = tEnv.sqlQuery(
      s"""
         | select *,current_watermark(create_time) from a
         |""".stripMargin
    )

    tEnv.createTemporaryView("view_res", resultTable)
    tEnv.toDataStream(resultTable).print()

**Comment by itinycheng** [comment]
@xyhc 
Source Connector 是通过`clickhouse-jdbc`发送查询语句到`ClickHouse`实现的（读取有限数据集），不支持类似`Flink-CDC`的功能；

**Comment by xyhc** [comment]
> @xyhc Source Connector 是通过`clickhouse-jdbc`发送查询语句到`ClickHouse`实现的（读取有限数据集），不支持类似`Flink-CDC`的功能；

明白！谢谢！

**Comment by xyhc** [comment]
感谢回复！


如果我需要实现持续地读取clickhouse表，有什么方法或者建议吗？



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "itinycheng/flink-connector-clickhouse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月30日(星期三) 中午11:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [itinycheng/flink-connector-clickhouse] 读取clickhouse的时候，不会一直读取，加载完了当前时间的数据，就退出了 (Issue #62)





 
@xyhc
 Source Connector 是通过clickhouse-jdbc发送查询语句到ClickHouse实现的（读取有限数据集），不支持类似Flink-CDC的功能；

**Comment by itinycheng** [comment]
> 感谢回复！ 如果我需要实现持续地读取clickhouse表，有什么方法或者建议吗？ &nbsp;


ClickHouse貌似没有类似Mysql binlog的功能，没办法做到实时监控数据变更的目的，除非二次开发；
另外可以前置一些代理服务（如nginx），监控实时数据的变化，这种得手动去解析日志，开发成本挺大的；
从业务出发，添加个列更新时间，然后通过定期的`select * from t where update_at > $time`，但Flink每次执行SQL都是一个新任务，也不能达到你的需求；

**Comment by ltylty** [comment]
> 感谢回复！ 如果我需要实现持续地读取clickhouse表，有什么方法或者建议吗？ &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "itinycheng/flink-connector-clickhouse" ***@***.***&gt;; 发送时间:&nbsp;2022年11月30日(星期三) 中午11:21 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [itinycheng/flink-connector-clickhouse] 读取clickhouse的时候，不会一直读取，加载完了当前时间的数据，就退出了 (Issue #62) @xyhc Source Connector 是通过clickhouse-jdbc发送查询语句到ClickHouse实现的（读取有限数据集），不支持类似Flink-CDC的功能； — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

如果有这样的需求应该用hudi
