### ISSUE TITLE
Tables in ClickhouseCatalog have no primary key

### ISSUE THREAD

**Issue by zidane-wcp** [itinycheng/flink-connector-clickhouse#64]
I found that the table in ClickhouseCatalog has no primary key, so I can't use ClickhouseCatalog in upsert mode. Could you please add the primary key of the table in ClickhouseCatalog?

**Comment by itinycheng** [comment]
Use option `catalog.ignore-primary-key=false`

**Comment by zidane-wcp** [comment]
> Use option `catalog.ignore-primary-key=false`

The order of the primary key columns in ClickhouseCatalog is not the same as in the table definition.

**Comment by itinycheng** [comment]
> > Use option `catalog.ignore-primary-key=false`
> 
> The order of the primary key columns in ClickhouseCatalog is not the same as in the table definition.

@zidane-wcp 
Yes, seems to follow the column definition order, refer to: [ClickHouseCatalog.getPartitionKeys](https://github.com/itinycheng/flink-connector-clickhouse/blob/master/src/main/java/org/apache/flink/connector/clickhouse/catalog/ClickHouseCatalog.java).
Are there any scenarios where the primary keys need to keep the order in which they are defined?
