### ISSUE TITLE
can not install this project 

### ISSUE THREAD

**Issue by qq994467433** [itinycheng/flink-connector-clickhouse#66]
can use mvn clean  but can not install  
![image](https://user-images.githubusercontent.com/40296964/218916627-93a594f5-1264-4394-bbec-7606644bc37d.png)

**Comment by FWLamb** [comment]
@qq994467433 Please use `mvn spotless: apply` to format the code before installing.

**Comment by qq994467433** [comment]
![image](https://user-images.githubusercontent.com/40296964/218919903-a46829bc-2ec1-4661-a340-ffdae2709c2b.png)
@FWLamb

**Comment by itinycheng** [comment]
1. Check whether `spotless-maven-plugin` is exists in your local repostory;
2. Pull the latest code and execute a maven command;

Other:
`mvn spotless:apply`, no space needed.
