### ISSUE TITLE
finkcdc同步到clickhouse，出现1002异常

### ISSUE THREAD

**Issue by h-mx** [itinycheng/flink-connector-clickhouse#67]
finkcdc同步到clickhouse，报异常org.apache.flink.connector.clickhouse.internal.executor.ClickHouseExecutor [] - ClickHouse executeBatch error, retry times = 1
ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: 10.240.1.155, port: 8123; Connection pool shut down
![image](https://user-images.githubusercontent.com/71714188/220011570-e0a65ee3-a56b-456e-9a78-bdcb4db95fb2.png)
![image](https://user-images.githubusercontent.com/71714188/220011755-2900dad3-920a-40dd-a585-a38cc72c0535.png)
然后线程池一直阻塞WAITING TIMED_WAITING
![image](https://user-images.githubusercontent.com/71714188/220012014-a3061349-f865-4792-a7ed-4eb285510222.png)
最后导致tsakmanager进程挂掉

我想知道该怎么解决这个问题

**Comment by itinycheng** [comment]
1.  报错是发生的数据发送给server的过程中，但从上文异常内容找不到`Http Pool shut down`的具体原因；
2. 你可以看下ClickHouse Server和Flink端的详细日志排查下；
