### ISSUE TITLE
请问一下  SSL 如何配置

### ISSUE THREAD

**Issue by taizilongxu** [itinycheng/flink-connector-clickhouse#68]

**Comment by itinycheng** [comment]
当前项目只支持Http

**Comment by itinycheng** [comment]
你可以通过`properties.*`方式给下层的`clickhouse-jdbc.jar`传ssl相关配置看看，但我不确定是否好用（在connector中有个矫正http端口的逻辑：[ClickHouseJdbcUtil.getActualHttpPort](https://github.com/itinycheng/flink-connector-clickhouse/blob/master/src/main/java/org/apache/flink/connector/clickhouse/util/ClickHouseJdbcUtil.java)）
