### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by weitianpei** [itinycheng/flink-connector-clickhouse#74]
![image](https://user-images.githubusercontent.com/30386282/234501259-f84848d1-52ab-4a52-adab-f76bd0426856.png)
请问这个参数是什么意思呢？意思是不是说，如果上游有更新，那么我们就会把更新的数据转换为
alter table tablename on cluster update ...这样的语句呢

**Comment by itinycheng** [comment]
> ![image](https://user-images.githubusercontent.com/30386282/234501259-f84848d1-52ab-4a52-adab-f76bd0426856.png) 请问这个参数是什么意思呢？意思是不是说，如果上游有更新，那么我们就会把更新的数据转换为 alter table tablename on cluster update ...这样的语句呢

update：将UPDATE_AFTER数据转换为alter table..
insert: 将UPDATE_AFTER数据转换为 insert into..
discard: 直接丢弃；

**Comment by weitianpei** [comment]
没有删除吗？
另外更新和删除操作会很慢吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月26日(周三) 晚上7:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [itinycheng/flink-connector-clickhouse] 问题咨询 (Issue #74)




  
 请问这个参数是什么意思呢？意思是不是说，如果上游有更新，那么我们就会把更新的数据转换为 alter table tablename on cluster update ...这样的语句呢
  
update：将UPDATE_AFTER数据转换为alter table..
 insert: 将UPDATE_AFTER数据转换为 insert into..
 discard: 直接丢弃；

**Comment by itinycheng** [comment]
@weitianpei 
与删除相关的配置：`sink.ignore-delete`；
Alter操作肯定慢，所以如果用`MergeTree`引擎时候，可以将`update_after`数据转为`insert`，后续通过`clickhouse`的`optimize`语句进行去重操作；
