### ISSUE TITLE
Publish project to maven central

### ISSUE THREAD

**Issue by AlexanderBobryakov** [itinycheng/flink-connector-clickhouse#75]
Can you add project publishing to maven central? If not, why not? 

Building and publishing your project to our own repository is very inconvenient, given the updating of your project and the release of new versions. We need to constantly keep an eye on new releases and fixes in this case.

**Comment by itinycheng** [comment]
Yeah, I know the inconvenience, but I don't have a suitable account available or the motivation to do this work.
The project is running smoothly and I have more study and work to do on my list so I don't want to pay more effort into this project.

Sorry to say these words.

**Comment by czy006** [comment]
@AlexanderBobryakov We are currently trying to contribute it to Apache, and it may be handed over to the official for processing in the future.
