### ISSUE TITLE
how to resolve flink.table.api.ValidationException err

### ISSUE THREAD

**Issue by xishuaidelin** [itinycheng/flink-connector-clickhouse#82]
I hava installed flink-clickhouse-connector and mvn clean install flink with new modified pom.xml which added the clickhouse-connector for dependency. it is ok that I create table with connector=clickhouse and connnect to my local clickhouse instance. however when I run the sql "select * from t1;" sql client throws the exception:

org.apache.flink.table.api.ValidationException: Could not find any factory for identifier 'clickhouse' that implements 'org.apache.flink.table.factories.DynamicTableFactory' in the classpath.

And t1 is table I created in clickhouse and registered in flink sql.

**Comment by itinycheng** [comment]
Hi @xishuaidelin 
The task you started seems unable to load `flink-clickhouse-connector`, is the connector placed in the `flink/lib` dir? 
You can go to check the startup log of `sql-client` to find the problem.
