### ISSUE TITLE
怎么可以加快同步速度

### ISSUE THREAD

**Issue by ysq5202121** [itinycheng/flink-connector-clickhouse#85]
如题

**Comment by ysq5202121** [comment]
我又2千万数据需要同步，发现半个小时才同步30万

**Comment by ysq5202121** [comment]
![image](https://github.com/itinycheng/flink-connector-clickhouse/assets/8586973/f2692820-6f01-4657-902b-9c835db093dc)

**Comment by itinycheng** [comment]
disable chain看下具体哪个operator慢；

**Comment by ysq5202121** [comment]
> disable chain看下具体哪个operator慢；
这个怎么操作 @itinycheng

**Comment by ysq5202121** [comment]
![image](https://github.com/itinycheng/flink-connector-clickhouse/assets/8586973/c60737f0-eb56-4a2c-b5c6-b4cbe1f1b4b3)
大数据似乎会报错

**Comment by ysq5202121** [comment]
传输不完整，2000W数据传输好多次总是不完整，漏数据
