### ISSUE TITLE
同步过去不是少了数据就是多了数据

### ISSUE THREAD

**Issue by ysq5202121** [itinycheng/flink-connector-clickhouse#86]
通过sqlserver cdc连接器同步到clickhouse ，
总是发现数据不是多了就是少了（ReplacingMergeTree，有唯一ID，执行合并后还是对不上两边的数据）
 'url' = '****',
    'database-name' = '***',
    'table-name' = '***',
    'sink.batch-size' = '10000',
    'use-local'='true',
    'sink.flush-interval' = '120s',
    'sink.max-retries' = '3'

**Comment by ysq5202121** [comment]
@itinycheng  很玄幻，感觉似乎这种同步并不好用。。。，无法掌控，哎

**Comment by ysq5202121** [comment]
解决方案设置主键ID为自增，执行数据删除都不会有问题

**Comment by gaoyan1998** [comment]
> @itinycheng 很玄幻，感觉似乎这种同步并不好用。。。，无法掌控，哎

+1 我也遇到了这个问题，我是直接从mysql jdbc导入，也是这问题，不是少就是多数据
