### ISSUE TITLE
cdc 写入 ck 的时候，是否支持先按照主键删除数据，在插入数据吗

### ISSUE THREAD

**Issue by mengfanyu** [itinycheng/flink-connector-clickhouse#87]
sink.update-strategy=update 时，表有 PARTITION BY 字段 不支持更新，执行update 会报错。

**Comment by itinycheng** [comment]
代码中生成alter语句是有对partition key进行排除的；

**Comment by mengfanyu** [comment]
![image](https://github.com/itinycheng/flink-connector-clickhouse/assets/20455125/f561870e-0781-4b8f-ba81-2c878c9cc366)
'sink.partition-key' = 'ORGANIZATION_CODE',  加了参数，更新时测试没有排除

**Comment by mengfanyu** [comment]
> 代码中生成alter语句是有对partition key进行排除的； 你可以测试找下具体原因，如有疑问请提供上下文和异常栈信息；

'sink.partition-key' = 'ORGANIZATION_CODE'  加了之后，在 生成 alter table  时没有去除此字段，是配置的不正确吗，请指导一下，谢谢

**Comment by mengfanyu** [comment]
解决了，ddl  PARTITIONED BY 使用错误
