### ISSUE TITLE
Maven Dependency

### ISSUE THREAD

**Issue by qiangtoudianyan** [itinycheng/flink-connector-clickhouse#9]
I want use it,but Maven Dependency not found.Maven repository url is ?

**Comment by itinycheng** [comment]
> I want use it,but Maven Dependency not found.Maven repository url is ?

The package isn't published to the central repo, need to compile it manually.
```
git clone git@github.com:itinycheng/flink-connector-clickhouse.git
cd flink-connector-clickhouse
mvn clean package -DskipTests
```

**Comment by qiangtoudianyan** [comment]
Thank you
