### ISSUE TITLE
有不有考虑实现折叠的功能

### ISSUE THREAD

**Issue by ysq5202121** [itinycheng/flink-connector-clickhouse#92]
在正常的数据库的CDC模式下，update、delete的操作都会带上数据更新或删除前的记录信息，如果想在ClickHouse里完成对应的update、delete的操作，只需要把更新或删除前的记录行带上sign为-1写进数据库即可，最新状态的数据带上sign为1写入即可

**Comment by itinycheng** [comment]
@ysq5202121 
当前以维护为主，做一些bugfix，没有添加新功能的计划；
