### ISSUE TITLE
似乎写入速度很慢

### ISSUE THREAD

**Issue by ysq5202121** [itinycheng/flink-connector-clickhouse#94]
![image](https://github.com/itinycheng/flink-connector-clickhouse/assets/8586973/02f9514e-b7d6-487f-a68f-c5265bee174a)
![image](https://github.com/itinycheng/flink-connector-clickhouse/assets/8586973/fb794a91-ef68-4835-a859-9ac8141f9b75)
![image](https://github.com/itinycheng/flink-connector-clickhouse/assets/8586973/62a42c09-2906-4f63-8c1e-42c3a9fcf75f)
![image](https://github.com/itinycheng/flink-connector-clickhouse/assets/8586973/10d08241-642e-47f2-bf7a-4f0215db756a)
不知道要怎么调整才能解决背压问题

**Comment by ysq5202121** [comment]
@itinycheng

**Comment by itinycheng** [comment]
Sink只是将数据写出给server，没什么多余的操作；
如果是`Upsert`操作看下是否是大量生成`Alter`语句导致的；

**Comment by ysq5202121** [comment]
@会有大量upsert

**Comment by itinycheng** [comment]
> @会有大量upsert

可能和这个upsert有关，当前connector会将update的数据解析成 `alter..update..`，执行alter操作对clickhouse来说比较重；
这个是clickhouse慢，最好将update转成insert操作并配合表引擎来规避update操作，看下readme中的`sink.update-strategy`

**Comment by ysq5202121** [comment]
@itinycheng 如果改成insert就会出现大量重复数据，同步需要时间，会造成一段时间出现数据不正确的问题，如果采用版本似乎又不支持，需要写代码

**Comment by ysq5202121** [comment]
难道我了

**Comment by itinycheng** [comment]
配合表引擎比如：ReplacingMergeTree这种是可以操作的，我这边也没太多别的方法；
