### ISSUE TITLE
[Feature request] Support lookup join in Flink 1.15

### ISSUE THREAD

**Issue by nylqd** [itinycheng/flink-connector-clickhouse#97]
Hello, I am a user of flink-clickhouse-connector and I am interested in using lookup join with ClickHouse tables in Flink 1.15. I noticed that the connector supports lookup join in Flink 1.16, but not in Flink 1.15. Is there any possibility to backport this feature to Flink 1.15? If so, what are the steps and challenges involved? If not, what are the reasons and limitations? Thank you for your time and attention.

**Comment by itinycheng** [comment]
Hi @nylqd 
The user-side interfaces of the lookup feature have significant changes in `Flink 1.16`, therefore it may be difficult to backport to an earlier version.
